### ISSUE TITLE
直播间声音串线

### ISSUE THREAD

**Issue by zhy978** [SeaLoong/BLRHH#100]
领取奖励的时候有概率出现声音串线，把其他直播间的声音播放出来了，而且还关不掉
**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chromium 版本 78.0.3904.108（正式版本） （64 位）
 - 脚本的版本: 2.4.9
 - 网络情况(网速): 一般
 - 其他浏览器插件/脚本: bilibili直播净化

**Comment by kenyeson** [comment]
今天刚更新完就出现声音串线，把其他直播间的声音播放出来了，而且还关不掉（也不是领取奖励的时候，就看着看着就出现）
使用环境:

浏览器: Chrome
浏览器版本: 领取奖励的时候有概率出现声音串线，把其他直播间的声音播放出来了，而且还关不掉
使用环境:

浏览器: Chrome
浏览器版本: 79.0.3945.130（正式版本） （64 位）
脚本的版本: 2.4.9
网络情况(网速): 一般
其他浏览器插件/脚本: bilibili直播净化
脚本的版本: 2.4.10
网络情况(网速): 一般
其他浏览器插件/脚本: bilibili直播间工具

**Comment by youwen233** [comment]
我也是这个问题2.4.10

**Comment by ikesky** [comment]
我昨天晚上开始也出现这个问题

**Comment by 553627045** [comment]
有这个问题.用CHROME的全局媒体控制可以调出直播窗口，确认串线

**Comment by xiaofine1122** [comment]
同发生这个问题，之前一直没有

**Comment by sciuridae564** [comment]
+1出现串线问题
使用环境：

浏览器：Chrome
浏览器版本：81.0.4044.129（正式版本） （64 位）
脚本的版本：2.4.10
网络情况（网速）：一般
其他浏览器插件/脚本：无

**Comment by wangchencom** [comment]
同发生这个问题，之前一直没有
浏览器：Chrome
版本 81.0.4044.138（正式版本） （64 位）
脚本的版本：2.4.10
网络情况（网速）：迅雷下载毛片中
其他浏览器插件/脚本：无

**Comment by XiaoZeYu** [comment]
> 领取奖励的时候有概率出现声音串线，把其他直播间的声音播放出来了，而且还关不掉
> **使用环境:**
> 
> * 浏览器: Chrome
> * 浏览器版本: Chromium 版本 78.0.3904.108（正式版本） （64 位）
> * 脚本的版本: 2.4.9
> * 网络情况(网速): 一般
> * 其他浏览器插件/脚本: bilibili直播净化

你可以尝试先将当前直播间声音关闭（指在直播间直播左下角的那个音量，禁用以后刷新一下，这样这些串线的声音就会以默认禁音的方式播放）然后再刷新重开直播间再打开直播间音量（刷新页面以后新的直播开启后都会以当前的直播间音量开启所以把自动刷新设置成0吧）

**Comment by duanluan** [comment]
俺也一样。我暂时将网站声音关了。

**Comment by wangchencom** [comment]
wow  好使了吗
