### ISSUE TITLE
开启插件时，直播间界面若不开播，会出现其他直播间的音频

### ISSUE THREAD

**Issue by chnoyw** [SeaLoong/BLRHH#108]
**描述bug**
简要描述所遇到的bug
开启插件，进入未开播的直播间界面挂机时，会出现其他直播间的音频
**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 正常进入一个未开播的直播间挂机

**预期行为**
开启直播间后正常挂机正常抽奖
**截图**

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chromium 79.0.3945.130 (正式版本) （64 位）
 - 脚本的版本: 2.4.10
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本
 - bug出现时间: (精确到分钟)

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by sandboxdream** [comment]
在正常开播的直播间同样可能突然出现其他直播间音频进入
重现bug：
加入直播间打开挂机助手，在连接弹幕服务器成功后其他直播间声音侵入。
有时候会正常，有的时候会有其他直播间声音侵入.

**Comment by DemiurgeZ** [comment]
我也有这个问题 不过我是在看直播的时候出现的 初始化之后有其他直播间的声音 过几分钟后会消失 然后再过几分钟又出现了

**Comment by AmyRose1288** [comment]
对的，最近经常发生开着抽奖的话会出现其他直播间的声音，而且还是无法消除的那种

**Comment by xuxu9110** [comment]
这个问题已经困扰我好几个月了……
