### ISSUE TITLE
双端观看任务失败

### ISSUE THREAD

**Issue by JimMoen** [SeaLoong/BLRHH#109]
**描述bug**
双端观看任务失败。

**重现bug**
1. 关闭移动端心跳并刷新网页，再次打开移动端心跳选项并再次刷新
2. 等待至少10分钟后依然显示未完成双端观看任务。

**预期行为**
应正常实现双端观看任务。

**使用环境:**
 - 浏览器: Chromium
 - 浏览器版本: Chromium 80.0.3987.122（正式版本）Arch Linux （64 位）
 - 脚本的版本: 2.4.10
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 已安装插件在本bug产生前未对脚本产生影响。但不排除其他插件更新后会产生影响。
 - bug出现时间: NaN

**Comment by Scriptbeta** [comment]
+1
![QQ截图20200310173719](https://user-images.githubusercontent.com/23139793/76299362-ecf1ca80-62f5-11ea-996a-32ce6fa8ccaa.png)
