### ISSUE TITLE
B站更新了小电视和摩天楼的奖励，自动抽奖失效了

### ISSUE THREAD

**Issue by Icarusradio** [SeaLoong/BLRHH#119]
**描述bug**
B站最近更新了小电视和摩天楼的奖励，现在两个礼物都是等待2分钟领取，然后辣条只有2天有效期。

**重现bug**
选择自己的直播间，开启脚本。如果出现小电视广播，等待2-3分钟，脚本并不会提示领奖。

**预期行为**
可以正常领取奖励。

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chrome 81.0.4044.113
 - 脚本的版本: 2.4.11
 - 网络情况(网速): 一般
 - 其他浏览器插件/脚本: 无

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by ITBillZ** [comment]
我也是遇到这个问题

**Comment by wanguaf2016** [comment]
同样的问题
