### ISSUE TITLE
银瓜子领取时间异常

### ISSUE THREAD

**Issue by hyacintho7** [SeaLoong/BLRHH#120]
**描述bug**
浏览任意直播间均出现bug

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 浏览直播间
2. 刷新页面，清除缓存均不能解决

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
![1](https://user-images.githubusercontent.com/46441367/80273045-8ee04180-8701-11ea-967f-9311a360c580.JPG)

**使用环境:**
 - 浏览器: 如Chrome
 - 版本 81.0.4044.92（正式版本） （64 位）
 - 脚本的版本: 如2.4.11
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: (精确到分钟)

**Comment by cos-fish** [comment]
你领瓜子的脚本能够使用吗 还是说你换过源了？
