### ISSUE TITLE
无法自动抽奖

### ISSUE THREAD

**Issue by QueenATK** [SeaLoong/BLRHH#129]
**描述bug**
N多的小电视抽奖都没有自动去领，全手动

**重现bug**
大概是最近的520小电视跟以前的不一样？

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chromium 74.0.3729.169
 - 脚本的版本: 如2.4.10
 - 网络情况(网速): 好
 - bug出现时间: 未知

**Comment by KillerQueen810** [comment]
遇到一模一样的问题，小电视不会去领
