### ISSUE TITLE
自动每日奖励失效

### ISSUE THREAD

**Issue by Mishasama** [SeaLoong/BLRHH#132]
**描述bug**
简要描述所遇到的bug
API换了

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 打开自动每日奖励

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
如果可以，请提供有关截图
![020627014323](https://user-images.githubusercontent.com/54498172/85880905-bfcf1680-b817-11ea-9639-dae5730da2af.png)

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Google Chrome 77.0.3865.120
 - 脚本的版本: 2.4.11
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: -
 - bug出现时间: 2020年6月27日 01:47:13

**其他**
若您有其他想要补充的内容，请在此说明
挺多应对挂机脚本做的改动，领辣条功能已经力不从心了。

**Comment by SeaLoong** [comment]
目前已恢复部分，至于投币功能还是得要用一些取巧的方法，之后再实现。

**Comment by SeaLoong** [comment]
3.1.7版本，每日奖励功能已完成
