### ISSUE TITLE
脚本初始化失败

### ISSUE THREAD

**Issue by QueenATK** [SeaLoong/BLRHH#135]
**描述bug**
打开直播间提示“初始化用户数据、直播间数据失败”

**重现bug**
打开任一个直播间

**预期行为**

**截图**

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chromium 74.0.3729.169
 - 脚本的版本: 2.4.11
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 

**其他**

**Comment by RangerQAQ** [comment]
遇到同样问题

**Comment by Seraph21345** [comment]
好像都是今天出现的呢

**Comment by cbisuper** [comment]
今天有同样的问题

**Comment by heinannn** [comment]
我也是今天出现问题 应该是b站改了什么

**Comment by zongying529** [comment]
我也是今天出的问题

**Comment by wanguaf2016** [comment]
我也是，我的甚至都没提示初始化失败

**Comment by Mishasama** [comment]
补充截图
![image](https://user-images.githubusercontent.com/54498172/87850640-d22b0480-c92c-11ea-8858-5b0649aa4e0a.png)

**Comment by heinannn** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeaLoong/Bilibili-LRHH"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 晚上6:28
收件人:&nbsp;"SeaLoong/Bilibili-LRHH"<Bilibili-LRHH@noreply.github.com&gt;;
抄送:&nbsp;"703989749"<703989749@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [SeaLoong/Bilibili-LRHH] 脚本初始化失败 (#135)



 补充截图

**Comment by heinannn** [comment]
刚刚好像没发出图




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeaLoong/Bilibili-LRHH"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 晚上6:28
收件人:&nbsp;"SeaLoong/Bilibili-LRHH"<Bilibili-LRHH@noreply.github.com&gt;;
抄送:&nbsp;"703989749"<703989749@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [SeaLoong/Bilibili-LRHH] 脚本初始化失败 (#135)



 补充截图

**Comment by ken3613** [comment]
遇到同样问题
脚本版本：2.4.4.16
Chrome版本：83.0.4103.116 (正式版本) （64 位） (cohort: Stable)

**Comment by Shirahae** [comment]
遇到同样问题，确认今天凌晨还一切正常，下午更新完Chrome发现的问题。
脚本版本：2.4.10
Chrome版本 84.0.4147.89（正式版本） （64 位）

**Comment by wanguaf2016** [comment]
现在脚本突然正常了。。
脚本版本：2.4.11
浏览器：Edge Chromium 84.0.522.40

**Comment by Seraph21345** [comment]
显示连接正常但是你们能领到辣条吗？

**Comment by AmyRose1288** [comment]
根据某魔改版github页面，B站有一天暗改了接口，但是一天后又改了回去

**Comment by Mishasama** [comment]
> 根据某魔改版github页面，B站有一天暗改了接口，但是一天后又改了回去

大概是APP爆炸了导致回滚吧……
