### ISSUE TITLE
firefox下无法领奖

### ISSUE THREAD

**Issue by Mioscout** [SeaLoong/BLRHH#139]
**描述bug**
简要描述所遇到的bug
Firefox下脚本工作不完全，仅签到和瓜子换硬币功能正常运作，其余功能不工作，直播间领奖功能设置中不出现
**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 使用Firefox78.02
2. 使用脚本

**预期行为**
简要描述进行以上操作后预期的脚本行为
正常工作
**截图**
如果可以，请提供有关截图
[
![QQ截图20200728220747](https://user-images.githubusercontent.com/61075611/88679101-afb19c00-d121-11ea-8c77-4c503c4e3598.jpg)
![QQ截图20200728215436](https://user-images.githubusercontent.com/61075611/88679100-afb19c00-d121-11ea-8b69-80908a217ecd.jpg)

](url)

**使用环境:**
 - 浏览器: firefox
 - 浏览器版本: firefox78.2
 - 脚本的版本: 如3
 - 网络情况(网速): 好/
 - 其他浏览器插件/脚本:测试关闭了会在同区域生效的脚本
 - bug出现时间: (精确到分钟)

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by SeaLoong** [comment]
建议给出控制台有关报错的截图，我刚发现Firefox有些东西不支持，不过不确定是否和这个有关。

**Comment by SeaLoong** [comment]
原因查明了，由于使用了Firefox尚未实现的语言特性，"宝箱"模块无法加载。至于为什么导致之后的模块不能加载我再查查。
支持情况如下图所示。
![support.png](https://i.loli.net/2020/07/29/p6zEO7TPbqJ4SHi.png)

提一嘴，我上面说的不支持的特性不是这一个，这个是之后发现的，看来Firefox差的有点多啊。

**Comment by Mioscout** [comment]
我倒是试着装回了2.41看了下，宝箱也是炸掉的。但是领奖还能正常运作。
另外控制台没任何报错提示，日志是空的，就直接没加载

**Comment by Mishasama** [comment]
老实Chrome吧，为什么要用那么落后的火狐……

**Comment by Mioscout** [comment]
![QQ截图20200730144925](https://user-images.githubusercontent.com/61075611/88890230-eac3e480-d273-11ea-9edc-1260f67832a9.jpg)
目前日志有报错了，是这样。
另外我用什么浏览器关上面那位什么事情，我不乐意用chrome还有错了？

**Comment by SeaLoong** [comment]
重写了加载方式，顺带把这个问题解决了。
