### ISSUE TITLE
搜狗浏览器油猴，3.0插件启动不了，完全没有反应

### ISSUE THREAD

**Issue by helynd** [SeaLoong/BLRHH#140]
没有签到，没有自动领奖，没有一切东西
仿佛这个插件不存在一样，是BUG嘛？

**Comment by SeaLoong** [comment]
可能是内核版本太低

**Comment by helynd** [comment]
不是哦！我用最新的谷歌浏览器，依然也是没有启动的迹象，就好像完全不存在一样。
很奇怪。
难道大家都使用正常？和网络运营商没关系吧？
我是长宽。

**Comment by helynd** [comment]
都是在第50行显示有个错误
InfoByUser?.property?
中间这个点那里显示错误
parsing error：unexpected token .

**Comment by hanjialiang** [comment]
我用的最新版Chrome，也遇到了相同的bug。第50行报错 eslint: null - Parsing error：Unexpected token .

**Comment by Mishasama** [comment]
> 不是哦！我用最新的谷歌浏览器，依然也是没有启动的迹象，就好像完全不存在一样。
> 很奇怪。
> 难道大家都使用正常？和网络运营商没关系吧？
> 我是长宽。

设置面板位置改了，不是在右下角了，是在土豪榜的上面仅仅一小行几个字。

**Comment by SeaLoong** [comment]
我想我查明原因了，昨天删Firefox不支持的代码时少删了东西

**Comment by helynd** [comment]
求更新！反正我是一直没有任何运转的感觉，一直都是不存在的样子。

**Comment by helynd** [comment]
https://github.com/SeaLoong/BLRHH/issues/140#issuecomment-665722050

插件就没成功启动过，哪里会有设置面板。。。

**Comment by SeaLoong** [comment]
其实我已经更了，不过要生效的话得等jsdelivr同步以及你的浏览器更新这部分的缓存。
这点确实是个问题，我有在考虑用更好的方法替代，不过这得花上一些时间了。

**Comment by helynd** [comment]
惊了，我还以为当场立刻马上就能更新一下的。。。
明天起床再看看吧

**Comment by helynd** [comment]
试了，谷歌浏览器能启动，虽然一直没有辣条，是不是破绽改了机制，不再有辣条了？
搜狗还是不能启动，估计是内核太低的缘故

**Comment by helynd** [comment]
错误依然还在，不知道什么时候能收到推送

**Comment by criedmumu** [comment]
> > 不是哦！我用最新的谷歌浏览器，依然也是没有启动的迹象，就好像完全不存在一样。
> > 很奇怪。
> > 难道大家都使用正常？和网络运营商没关系吧？
> > 我是长宽。
> 
> 设置面板位置改了，不是在右下角了，是在土豪榜的上面仅仅一小行几个字。

还是没找到。。

**Comment by helynd** [comment]
3.0有chrome内核要求，不到是启动不了的。我用最新版的谷歌浏览器才启动了。
新的设置在七日榜上面，没有就是插件没启动
好像现在小电视都没有辣条了，破绽可以倒闭了

**Comment by vi4389** [comment]
> 3.0有chrome内核要求，不到是启动不了的。我用最新版的谷歌浏览器才启动了。
> 新的设置在七日榜上面，没有就是插件没启动
> 好像现在小电视都没有辣条了，破绽可以倒闭了

更新chrome浏览器能用了
