### ISSUE TITLE
Firefox 71.0 模块运行失败

### ISSUE THREAD

**Issue by dbcliu** [SeaLoong/BLRHH#144]
FF并非测试过的平台，但是还是汇报下：
系统版本：Windows 10 19041.388
浏览器：Firefox 79.0
油猴插件：Tempermonkey 4.11.6117
报错提示：模块Treasurebox导入失败 以及 Worker加载失败
右侧按钮有出现，领取瓜子等没反应
Pakku已经禁用

**Comment by Mishasama** [comment]
#139 发issue前建议先看看issues列表，不然你会做无用功的。

**Comment by dbcliu** [comment]
> 
> 
> #139 发issue前建议先看看issues列表，不然你会做无用功的。

喔 之前的靠前我以为是不相关的问题 close掉吧
