### ISSUE TITLE
TreasureBox导入失败，尝试 script 标签加载？

### ISSUE THREAD

**Issue by Tinard** [SeaLoong/BLRHH#145]
**描述bug**
插件无法运行，两个问题：
1. TreasureBox导入失败，尝试 script 标签加载？如下图！
2. pakku 插件不兼容
**截图**
![6531597128050_ pic](https://user-images.githubusercontent.com/23216991/89866531-4a11e500-dbe2-11ea-849f-70872712a4b0.jpg)

**使用环境:**
 - 浏览器: Chrome MacPro

**Comment by SeaLoong** [comment]
emmm这可能是正好碰上我在改代码进行测试
