### ISSUE TITLE
希望能加上之前的自动投币功能

### ISSUE THREAD

**Issue by realJackWang** [SeaLoong/BLRHH#146]
就每天投5个币加经验的功能，感谢大佬

**Comment by SeaLoong** [comment]
投币有点麻烦，其他三个倒是先做了。之后我再弄弄吧。

**Comment by SeaLoong** [comment]
3.1.7版本已实现
Commit [f3d48f](https://github.com/SeaLoong/BLRHH/commit/f3d48fa0b380ae5564ef170d8e6a46d2320dbd52)
