### ISSUE TITLE
针对不同时区进行适配

### ISSUE THREAD

**Issue by yowanep** [SeaLoong/BLRHH#149]
**描述bug**
在非GMT+8地区执行脚本如进入零点之后脚本会认为已经是第二天，触发进行签到开箱子等操作，可能会触发封禁问题
希望在设置中提供针对不同时区进行设置或者几点之后开始进行相关操作的选项设置

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 将系统时间设定为非GMT+8时区
2. 执行脚本并等待跨过当日24点时段之后

**预期行为**
-

**截图**
-

**使用环境:**
 - 浏览器: edge
 - 浏览器版本: edge Chromium 84.0.522.63
 - 脚本的版本: 3.1.3
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: -
 - bug出现时间: -

**其他**
-

**Comment by SeaLoong** [comment]
我怎么记得我做过时区修正来着，时间不正确吗

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/91317766-66726c00-e7f5-11ea-86f0-21140b70cfde.png)
疑似同样问题

**Comment by olalaha** [comment]
类似的时区问题.

国内换天后, 我这里还没换天的时候, 脚本的各种功能会回复"今日已完成", 但是不会进行任何操作.

**Comment by Mishasama** [comment]
嗯……会一直刷日志消耗大量的系统资源，问题挺严重的，建议优先修复。

**Comment by SeaLoong** [comment]
已确认是bug，之前做的时区修正的符号加减算错了TAT

**Comment by SeaLoong** [comment]
已修复， 见[cfdafcd](https://github.com/SeaLoong/BLUL/commit/cfdafcd61e07dcd64eab04b649b3b949e9fd8432)
这次修复不更新版本号，待CDN缓存更新后重新安装（或等油猴自动更新resource）即可生效。
