### ISSUE TITLE
特殊直播间不显示但会阻止其它直播间正常运行

### ISSUE THREAD

**Issue by Mishasama** [SeaLoong/BLRHH#153]
# 描述bug
简要描述所遇到的bug
在某些定制页面样式的直播间（比如最近提莫的1314）会无法显示脚本的界面，但是却会让脚本在后台挂着并且激活，导致了另外开其它普通样式的直播间页面时出现“已在其它直播间运行”这样的字样，并且不显示脚本界面。

# 重现bug
说明您在进行了怎样的操作后出现了bug
1. 进入1314
2. 进入自己的直播间

# 预期行为
要么把界面植入的方式跳脱直播间的样式框架，作为额外的元素独立存在。
要么维持老的情况不能适配非标准样式的直播间，但让这些无法显示界面的直播间也不执行脚本，避免其它标准样式的直播间无法运行。

# 使用环境:
 - 浏览器: Chrome
 - 浏览器版本: Chrome 85.0.4183.83
 - 脚本的版本: 3.1.4
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: -
 - bug出现时间: -

# 其他
毕竟都3代了…如果可以的话还是希望能通吃所有样式，这样就不用特意另外去挂小主播的直播间节省系统资源了。
相关 Issue #74

**Comment by SeaLoong** [comment]
这个其实也是做了适配的，但是好像有点问题，我等会改改

**Comment by SeaLoong** [comment]
已修复，[c48fc0](https://github.com/SeaLoong/BLUL/commit/c48fc02a370360abe3fa23b5a408d8b4ade57397)
