### ISSUE TITLE
心跳-移动端账号未登录

### ISSUE THREAD

**Issue by Mishasama** [SeaLoong/BLRHH#157]
**描述bug**
心跳-移动端账号未登录

**重现bug**
1. 启用心跳

**预期行为**
没有出错提示

**截图**
![image](https://user-images.githubusercontent.com/54498172/94836762-50884480-044e-11eb-92cb-eb4894ef3049.png)

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: 85.0.4183.121
 - 脚本的版本: 3.1.5
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 每个心跳间隔

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by SeaLoong** [comment]
这个是因为缓存的access_token过期了，但是当前时间还没有到过期时间导致的，至于为什么会这样我也不清楚，过期时间戳是从B站获取access_token的时候一起给的。
暂时先手动把过期时间戳修改为小于当前时间戳的值可以解决。
考虑在加载的时候验证一次token或者弄个手动刷新来解决。

**Comment by Mishasama** [comment]
B站提供的时间戳是不是不带时区的？如果是，可能还是时区不是+8的问题。

另外…这个功能现在还有什么用么……双端观看的任务已经没了。

**Comment by SeaLoong** [comment]
已尝试改变记录的过期时间来规避这个问题，目前方法是把B站给的有效期的一半作为真的有效期，应该可以减少这种问题。
见 Commit [f0ca38](https://github.com/SeaLoong/BLUL/commit/f0ca38af522fb9dbce76026c8addb5547f657a77)

这个功能（指移动端心跳）现在确实没用了，不过这个获取移动端token的指不定还有用，都保留也没啥问题吧（万一哪天又有用了呢？）
