### ISSUE TITLE
新直播间样式适配

### ISSUE THREAD

**Issue by Mishasama** [SeaLoong/BLRHH#160]
**描述bug**
启动脚本会影响所有的拖动事件无法实现（如音量条、滚动条等），变成只能点击，所有控件无法捕获到按下拖动的事件。

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 启动脚本
2. **先打开一个直播间，并确保脚本正常运行**
3. **再打开另一个直播间**
4. **确保测试的直播间页面处于脚本识别到其它页面在运行而不继续运行**
2. 对被测试的直播间页面用鼠标左键点击音量条按钮并拖动
3. 或者拖动右侧关注主播的浮窗列表的滚动条（能移动，但没了平滑）

**预期行为**
简要描述进行以上操作后预期的脚本行为
不影响原有功能

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chrome 87.0.4280.88
 - 脚本的版本: 3.1.9
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: -
 - bug出现时间: 2020年12月16日

**其他**
若您有其他想要补充的内容，请在此说明
直播间页面样式和播放器今天均有变化，需要重新适配。

**Comment by SeaLoong** [comment]
这个我没法复现，测试了一下都正常的（Windows下使用鼠标操作）。后续我会再看看。

**Comment by Mishasama** [comment]
> 这个我没法复现，测试了一下都正常的（Windows下使用鼠标操作）。后续我会再看看。

更新了一下复现步骤，你再测试下……
我这边用另外一个浏览器profile又没问题……
但是有问题的那个禁用了所有其它插件和脚本都一样是这样😓

**Comment by SeaLoong** [comment]
这个问题确认了，不过我这的现象是除了播放器以外的部分都没加载出来，并且播放器的功能不完全有效（昨天没关注播放器的功能），可在控制台看到有错误，不过应该是我发现的问题一样。
