### ISSUE TITLE
已经关了广告过滤，但还是不能自动抽奖

### ISSUE THREAD

**Issue by 273514282** [SeaLoong/BLRHH#72]
**描述bug**
已经按要求关了广告过滤了，但还是不能自动抽奖，领银瓜子和签到等功能都没有问题
有提示跨域和一个函数没定义，如下:
![image](https://user-images.githubusercontent.com/16009773/59019003-c5a73200-8879-11e9-9c2e-4decfc7f26c7.png)

**使用环境:**
 - 浏览器: QQ浏览器
 - 浏览器版本: 10.4.1（3505）
 - 脚本的版本: 2.3.18
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 进入直播间就报

**Comment by g2384** [comment]
试试chrome呗

**Comment by SeaLoong** [comment]
这个问题我也不清楚是什么原因导致的，一般都是广告过滤插件会拦脚本加载，当然也有可能是浏览器的一些内置插件引起的问题。

**Comment by 8MiYile** [comment]
推荐用Cent或者Chrome
